// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE_QMG5oN_P-lzlRxB-NJPD3SyF2C63Oo',
    appId: '1:189781542716:web:b408cb6698c325062dc039',
    messagingSenderId: '189781542716',
    projectId: 'maintenance-app-74304',
    authDomain: 'maintenance-app-74304.firebaseapp.com',
    storageBucket: 'maintenance-app-74304.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvdRn6YNkcpIDKxByjGAIFnhFKXaUAQxw',
    appId: '1:189781542716:android:fb8a7c6b8862e0ec2dc039',
    messagingSenderId: '189781542716',
    projectId: 'maintenance-app-74304',
    storageBucket: 'maintenance-app-74304.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE_QMG5oN_P-lzlRxB-NJPD3SyF2C63Oo',
    appId: '1:189781542716:web:e2d9ef7f4838c5b42dc039',
    messagingSenderId: '189781542716',
    projectId: 'maintenance-app-74304',
    authDomain: 'maintenance-app-74304.firebaseapp.com',
    storageBucket: 'maintenance-app-74304.firebasestorage.app',
  );
}
